# Generated by Django 4.2.30 on 2026-08-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_stockadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.CharField(blank=True, help_text='e.g. HDMI Cable, Dell XPS 15, HP EliteBook', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.CharField(blank=True, help_text='e.g. 1.5m, 2m, 16GB/512GB, Gen 12 i7', max_length=100, null=True),
        ),
    ]
