# Generated by Django 4.2.30 on 2026-08-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_product_group_product_variant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('store', 'product_group', 'variant')},
        ),
    ]
