# Generated by Django 4.2.30 on 2026-08-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('store', 'product_name', 'variant')},
        ),
    ]
