# Generated by Django 4.2.30 on 2026-08-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='grace_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='installment',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='installment',
            name='late_fee_applied',
            field=models.BooleanField(default=False),
        ),
    ]
