# Generated by Django 4.2.30 on 2026-08-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Bank account number (shown on Tax Invoice)', max_length=100),
        ),
    ]
