# Generated by Django 4.2.30 on 2026-06-22 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_saleitem_product'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='store.store'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('store', 'phone')},
        ),
    ]
