# Generated by Django 4.2.30 on 2026-08-13 07:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0003_stockadjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='My Company', max_length=200)),
                ('company_phone', models.CharField(blank=True, max_length=30)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_address', models.TextField(blank=True)),
                ('company_tin', models.CharField(blank=True, max_length=50, verbose_name='Company TIN')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='settings/logo/')),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('currency_symbol', models.CharField(default='TSh', max_length=5)),
                ('default_tax_percent', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('allow_negative_stock', models.BooleanField(default=False)),
                ('require_customer_on_sale', models.BooleanField(default=False)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('auto_print_receipt', models.BooleanField(default=True)),
                ('invoice_prefix', models.CharField(default='INV', max_length=20)),
                ('proforma_prefix', models.CharField(default='PRO', max_length=20)),
                ('delivery_prefix', models.CharField(default='DN', max_length=20)),
                ('default_invoice_terms', models.TextField(blank=True, default='Payment is due within 30 days. Thank you for your business.')),
                ('default_bank_account', models.TextField(blank=True, help_text='Bank name, Account number, etc.')),
                ('session_timeout_minutes', models.PositiveIntegerField(default=60)),
                ('enable_audit_log', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_header', models.TextField(blank=True, help_text='Appears at the top of receipts')),
                ('receipt_footer', models.TextField(blank=True, help_text='Thank you message / return policy')),
                ('show_cashier_name', models.BooleanField(default=True)),
                ('show_tax_breakdown', models.BooleanField(default=True)),
                ('enable_tips', models.BooleanField(default=False)),
                ('default_payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile', 'Mobile Money'), ('bank', 'Bank Transfer')], default='cash', max_length=30)),
                ('track_expiry', models.BooleanField(default=False)),
                ('allow_stock_transfer', models.BooleanField(default=True)),
                ('low_stock_alert', models.BooleanField(default=True)),
                ('daily_sales_email', models.BooleanField(default=False)),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='store.store')),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
