# Generated by Django 4.2.30 on 2026-08-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclosing',
            name='advance_payments',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Money paid in advance by customers', max_digits=14),
        ),
        migrations.AddField(
            model_name='dailyclosing',
            name='maintenance_income',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Money from customer device maintenance / repair', max_digits=14),
        ),
    ]
