# Generated by Django 4.2.30 on 2026-08-22 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_dailyclosing_advance_payments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashout',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dailyclosing',
            name='advance_payments',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Money paid in advance by customers', max_digits=16),
        ),
        migrations.AlterField(
            model_name='dailyclosing',
            name='bank_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='dailyclosing',
            name='cash_in_hand',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='dailyclosing',
            name='lipa_namba_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='dailyclosing',
            name='maintenance_income',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Money from customer device maintenance / repair', max_digits=16),
        ),
        migrations.AlterField(
            model_name='dailyclosing',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='dailyclosing',
            name='stock_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='dailyclosing',
            name='stock_out',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
