# Generated by Django 4.2.30 on 2026-07-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('warehouse_staff', 'Warehouse Staff')], default='admin', max_length=20),
        ),
    ]
