# Generated by Django 4.2.30 on 2026-08-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='For SMS e.g. 0712345678', max_length=20, null=True),
        ),
    ]
