# Generated by Django 4.2.30 on 2026-08-05 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_stockadjustment'),
        ('orders', '0002_alter_supplierorderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorderitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Existing product (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
        migrations.AlterField(
            model_name='supplierorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Expected / quoted unit price', max_digits=12),
        ),
    ]
