# Generated by Django 4.2.30 on 2026-08-27 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_added', models.BooleanField(default=True)),
                ('product_updated', models.BooleanField(default=True)),
                ('product_deleted', models.BooleanField(default=True)),
                ('stock_adjustment', models.BooleanField(default=True)),
                ('low_stock', models.BooleanField(default=True)),
                ('out_of_stock', models.BooleanField(default=True)),
                ('order_created', models.BooleanField(default=True)),
                ('supplier_order_received', models.BooleanField(default=True)),
                ('store_created', models.BooleanField(default=True)),
                ('new_sale', models.BooleanField(default=True)),
                ('sales_return', models.BooleanField(default=True)),
                ('invoice_paid', models.BooleanField(default=True)),
                ('installment_created', models.BooleanField(default=True)),
                ('installment_reminder', models.BooleanField(default=True)),
                ('installment_completed', models.BooleanField(default=True)),
                ('large_cash_out', models.BooleanField(default=True)),
                ('daily_report', models.BooleanField(default=True)),
                ('user_registered', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_notification_preference_per_user'),
        ),
    ]
